primer commit del seutUp
wolox-training/gs-react-native pull request #1
Opened 2018-09-05 19:54 UTC by guillewolox00126

## Summary
– comentario
subo el setup del proyecto

## Screenshot
![captura de pantalla 2018-09-05 a la s 16 52 31](https://user-images.githubusercontent.com/42941989/45117500-31624000-b12c-11e8-9845-d052f107b71b.png)

## Trello Card
https://trello.com/c/HPwzsXKd/11-setup-del-proyecto

2018-09-05 20:03 UTC, mmamaniwolox requested changes

2018-09-05 20:03 UTC, mmamaniwolox commented on index.html
> +</html>
Add a tailing line at the end of the file. Always in html and css

2018-09-05 20:03 UTC, mmamaniwolox commented on scss/application.scss
> +  }
Add a tailing line

2018-09-05 22:58 UTC, mmamaniwolox requested changes
Name both branch and commits in english. Everything must be in english :P

2018-09-05 22:58 UTC, mmamaniwolox commented on scss/application.scss
> +.title{
Add an space between title and the `{`

2018-09-05 22:58 UTC, mmamaniwolox commented on scss/application.scss
> +  color:red;
Add an space between `color:` and `red`

2018-09-06 12:29 UTC, mmamaniwolox approved these changes

2018-09-06 12:30 UTC, FrankIglesias approved these changes

2018-09-06 12:37 UTC, merged