Page titles
wolox-training/gs-react-native pull request #3
Opened 2018-09-06 18:21 UTC by guillewolox00126

##Summary
add branch page-titles

##Screenshot
![captura de pantalla 2018-09-06 a la s 15 13 57](https://user-images.githubusercontent.com/42941989/45176961-f9203780-b1e7-11e8-9dc3-5bfdb6774d1d.png)

##Trello Card
https://trello.com/c/STWBkHIf/21-page-titles

2018-09-06 18:28 UTC, mmamaniwolox requested changes

2018-09-06 18:28 UTC, mmamaniwolox commented on scss/titles.scss
> +  margin:10px;
Add a space between `:` and `10`

2018-09-06 18:28 UTC, mmamaniwolox commented on scss/styles.scss
> +  left:-45px;
Add a space after `:`

2018-09-06 18:28 UTC, mmamaniwolox commented on scss/titles.scss
> +.title-container{
Add a space before `{`

2018-09-06 18:28 UTC, mmamaniwolox commented on index.html
> +  <img src="images/triangle.svg" width="120" height="90">
Move width and height to titles.scss

2018-09-06 18:28 UTC, mmamaniwolox commented on scss/styles.scss
> +.title {
This should be in `titles.scss` file

2018-09-06 18:42 UTC, mmamaniwolox requested changes

2018-09-06 18:42 UTC, mmamaniwolox commented on index.html
> +<div class="title-container">
This should be tabbed, 2 more spaces to right, same with below element

2018-09-06 18:42 UTC, mmamaniwolox commented on scss/styles.scss
> +  color: black;
Create a `colors.scss` file, import it in `application.scss` and use it

2018-09-07 14:52 UTC, mmamaniwolox requested changes

2018-09-07 14:52 UTC, mmamaniwolox commented on index.html
> +  <p class="title">Front-End Tools</p>
As this is a title, you could use `<h1>` here

2018-09-07 14:52 UTC, mmamaniwolox commented on scss/color.scss
> +$color-black: #000000;
This is a detail, but you can just write `#000` and will work the same. It works the same with repeated hexs, like `#FFF`

2018-09-07 14:52 UTC, mmamaniwolox commented on scss/titles.scss
> +
delete one of this spaces

2018-09-07 14:52 UTC, mmamaniwolox commented on scss/titles.scss
> +  top: 60px;
This is a relative position element, dont use left or top in this one. To move it use margin or padding. But dont focus on this in this PR, just remove them (top and left). We will see how to position the title once we start adding things

2018-09-07 14:52 UTC, mmamaniwolox commented on scss/titles.scss
> +  z-index: 1;
This is not needed, you just have to use the z-index in the image

2018-09-07 14:52 UTC, mmamaniwolox commented on scss/titles.scss
> +  left: -80px;
Try to find a positive bottom and right position instead of negative top and left

2018-09-07 15:31 UTC, mmamaniwolox approved these changes

2018-09-07 17:04 UTC, FrankIglesias requested changes

2018-09-07 17:04 UTC, FrankIglesias commented on scss/titles.scss
> +  display: inline-block;
this is unnecessary

2018-09-07 17:04 UTC, FrankIglesias commented on scss/titles.scss
> +  &:after {
`&::after`

2018-09-08 00:09 UTC, FrankIglesias requested changes

2018-09-08 00:09 UTC, FrankIglesias commented on scss/titles.scss
> +  &:before {
`&::before`

2018-09-10 13:06 UTC, FrankIglesias approved these changes

2018-09-10 13:12 UTC, merged