first commit of content-layout
wolox-training/gs-react-native pull request #5
Opened 2018-09-10 20:33 UTC by guillewolox00126

##Summary
add content-layout

##Screenshot
![captura de pantalla 2018-09-10 a la s 17 31 53](https://user-images.githubusercontent.com/42941989/45322732-8aace380-b51f-11e8-9007-6ec640d9ad7f.png)

##Trello Card
https://trello.com/c/mpZXF7Q8/23-content-layout

2018-09-10 23:53 UTC, mmamaniwolox requested changes

2018-09-10 23:53 UTC, mmamaniwolox commented on scss/tech.scss
> + .container-technologies{
space

2018-09-10 23:53 UTC, mmamaniwolox commented on scss/tech.scss
> +  margin: 0 0 0 60px;
margin-left?

2018-09-10 23:53 UTC, mmamaniwolox commented on scss/tech.scss
> +
Delete this empty line

2018-09-10 23:53 UTC, mmamaniwolox commented on scss/tech.scss
> + .body{
Space before curly braces

2018-09-10 23:53 UTC, mmamaniwolox commented on scss/tech.scss
> + }
Here you have an extra space

2018-09-11 13:14 UTC, mmamaniwolox approved these changes

2018-09-11 13:20 UTC, FrankIglesias approved these changes

2018-09-11 13:40 UTC, merged