Navbar
wolox-training/gs-react-native pull request #7
Opened 2018-09-11 17:34 UTC by guillewolox00126

#Summary
add navbar

#Screenshot
![captura de pantalla 2018-09-11 a la s 14 33 07](https://user-images.githubusercontent.com/42941989/45376980-a66fc280-b5cf-11e8-9951-0574260f4efc.png)

##Trello Card
https://trello.com/c/a1JdMQDB/13-navbar

2018-09-11 17:39 UTC, mmamaniwolox requested changes

2018-09-11 17:39 UTC, mmamaniwolox commented on scss/color.scss
> +$color-white: #fff;
Use uppercase here #FFF

2018-09-11 17:39 UTC, mmamaniwolox commented on scss/navbar.scss
> +  width: 120px;
Use height or width, that will be enought

2018-09-11 17:39 UTC, mmamaniwolox commented on scss/navbar.scss
> +
Delete this empty line

2018-09-11 19:25 UTC, mmamaniwolox requested changes

2018-09-11 19:25 UTC, mmamaniwolox commented on index.html
>    <h1 class="title">Front-End Tools</h1>
You miss a tabbing in all div body

2018-09-11 19:25 UTC, mmamaniwolox commented on index.html
> +  <div class="body">
Use a different class name, page-contetnt for example. Body is an html element, this may be confusing

2018-09-11 19:25 UTC, mmamaniwolox commented on scss/navbar.scss
> +  width: 120px;
Use only height or width

2018-09-11 19:49 UTC, mmamaniwolox approved these changes

2018-09-11 19:54 UTC, mmamaniwolox requested changes

2018-09-11 19:54 UTC, mmamaniwolox commented on index.html
> +    <img class="image-navbar" src="images/wolox_logo.svg" alt="Wolox logo">
Close this and the other img tabs `/>`

2018-09-11 19:54 UTC, mmamaniwolox commented on scss/tech.scss
> +  margin: 0 30px 30px 30px;
`0 30px 30px` instead

2018-09-11 19:54 UTC, mmamaniwolox commented on scss/titles.scss
> +  margin: 160px 80px 80px 80px;
`160px 80px 80px` instead

2018-09-12 13:12 UTC, mmamaniwolox requested changes

2018-09-12 13:12 UTC, mmamaniwolox commented on index.html
> +  <div class="body">
Use a more descriptive css class, body is an html element

2018-09-12 13:50 UTC, mmamaniwolox approved these changes

2018-09-12 19:04 UTC, FrankIglesias commented on scss/navbar.scss
> +  top: 0px;
top: 0;

2018-09-12 19:04 UTC, FrankIglesias commented on scss/navbar.scss
> +  left: 0px;
left: 0;

2018-09-12 19:09 UTC, FrankIglesias approved these changes

2018-09-12 19:10 UTC, merged