Redesign of page
wolox-training/gs-react-native pull request #9
Opened 2018-09-12 19:18 UTC by guillewolox00126

##Summary
add Redesign of page

##Screenshot
![captura de pantalla 2018-09-12 a la s 16 17 11](https://user-images.githubusercontent.com/42941989/45447897-58c68900-b6a7-11e8-9ec9-
91df984b3cee.png)

##Trello Card
https://trello.com/c/TBXJcGJB/12-redise%C3%B1o-de-la-p%C3%A1gina

2018-09-12 19:23 UTC, mmamaniwolox requested changes
Try to move the border right more to the center no that close to the techo-content

2018-09-12 23:25 UTC, mmamaniwolox requested changes

2018-09-12 23:25 UTC, mmamaniwolox commented on scss/tech.scss
> +  grid-auto-flow: row;
I think this is default prop, try without this

2018-09-13 13:24 UTC, mmamaniwolox approved these changes

2018-09-13 13:49 UTC, FrankIglesias requested changes

2018-09-13 13:49 UTC, FrankIglesias commented on scss/tech.scss
> +  height: 600px;
Height 100%

2018-09-13 13:49 UTC, FrankIglesias commented on scss/tech.scss
> +  padding-top: 150px;
Why this padding?

2018-09-13 15:00 UTC, FrankIglesias approved these changes

2018-09-13 15:25 UTC, merged